[package]
name = "image-features"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lstsq = "0"
image = "0"
rayon = "1"
anyhow = "1"
nalgebra = "0"
parking_lot = "0"
